### ISSUE TITLE
verify: unable to get issuer certificate

### ISSUE THREAD

**Issue by notbrokenjemma** [perl-net-saml2/perl-Crypt-OpenSSL-Verify#9]
When verifying 1 cert against another, this error is thrown by 0.19 but not by 0.10

**Comment by timlegge** [comment]
try adding strict_certs => 0

**Comment by timlegge** [comment]
This likely implies a self signed certificate or the inability to find the root.  Is the certificate self signed or is there an intermediate certificate that you are missing in the chain?

**Comment by notbrokenjemma** [comment]
The certificate is an intermediate, being verified against a root cert bundle. Adding strict_certs => 0 did not change the result.

**Comment by timlegge** [comment]
Are you able to share the certificates.  Just the public cert of course

**Comment by notbrokenjemma** [comment]
Apologies, my initial explanation was incorrect.

The cert being verified against is an intermediate cert. I can't share this cert with you, but will work on a reproduction that I can share.

**Comment by notbrokenjemma** [comment]
https://gist.github.com/marcbradshaw/099927317fcf7682fc21c09288c1f564

**Comment by timlegge** [comment]
I can look later today but take a look at t/02-good-cert.t.  The root needs to be appended to the intermediate

**Comment by timlegge** [comment]
I have a fix for you.  I modified your script and it runs fine with the changes:

https://gist.github.com/timlegge/8926b9e26613dc77aad229eb29ae2608

Would you mind if I add that to the tests in the module?  It will help with the validation of public certs

**Comment by timlegge** [comment]
fixed in master and will be released soon

**Comment by timlegge** [comment]
Fixed in 0.20-TRIAL on cpan - will review the cpantester results and release production tomorrow

**Comment by timlegge** [comment]
Version 0.20 released
